version: "3.8"

services:
  backend:
    image: heilrose/backend-agronect:${VERSION}
    container_name: backend-agronect
    restart: always
    ports:
      - "3000:3000"
    environment:
      DB_NAME: agronect-skripsi
      DB_USER: doadmin
      DB_PASSWORD: $DB_PASSWORD
      DB_HOST: database-skripsi-do-user-18408833-0.m.db.ondigitalocean.com
      DB_PORT: 25060
      JWT_SECRET: "baguskeren77"
      REFRESH_TOKEN_SECRET: "bagusasik77"
